import 'tailwindcss/tailwind.css';
import '../styles/global.css';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({ subsets: ['latin'] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
