import Head from 'next/head'
import { Header } from "@/common/header/Header";
import { Hero } from "@/components/sections/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - XXX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
    </>
  )
}
